services:
  pose-feature-extractor-worker:
    build: ./workers/pose_feature_extractor_worker
    depends_on:
      rabbitmq:
        condition: service_healthy
      minio-setup:
        condition: service_completed_successfully

  score-analyzer-worker:
    build: ./workers/score_analyzer_worker
    depends_on:
      rabbitmq:
        condition: service_healthy

  spring-api:
    build: ./api/liftform
    environment:
      - SPRING_PROFILES_ACTIVE=local
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
      minio-setup:
        condition: service_completed_successfully

  frontend:
    build: ./frontend
    environment:
      - API_PROXY_TARGET=http://spring-api:8080
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - spring-api