services:
  pose_feature_extractor_worker:
    build: ./workers/pose_feature_extractor_worker
    depends_on:
      rabbitmq:
        condition: service_healthy
      minio-setup:
        condition: service_completed_successfully

  score_analyzer_worker:
    build: ./workers/score_analyzer_worker
    depends_on:
      rabbitmq:
        condition: service_healthy

  spring_api:
    build: ./api/liftform
    environment:
      - SPRING_PROFILES_ACTIVE=local
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
      minio-setup:
        condition: service_completed_successfully