services:
  spring-api:
    image: your-ecr/liftform-api:latest
    environment:
      - SPRING_PROFILES_ACTIVE=prod
  pose-feature-extractor-worker:
    image: your-ecr/liftform-api:latest
  score-analyzer-worker:
    image: your-ecr/liftform-score-analyzer-worker:latest