CREATE TABLE IF NOT EXISTS TB_USER (
    ID UUID PRIMARY KEY DEFAULT uuidv7(),
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT now()
);