CREATE TABLE TB_REFRESH_TOKEN (
    ID BIGSERIAL PRIMARY KEY,
    USER_ID UUID NOT NULL,
    TOKEN_HASH TEXT NOT NULL,
    EXPIRES_AT TIMESTAMP NOT NULL,
    REVOKED BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP DEFAULT now(),
    FOREIGN KEY (USER_ID) REFERENCES TB_USER(ID) ON DELETE CASCADE
);