CREATE TABLE IF NOT EXISTS TB_REFRESH_TOKEN (
    TOKEN_HASH VARCHAR(255) PRIMARY KEY,
    USER_ID UUID NOT NULL,
    EXPIRES_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    REVOKED BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT now(),
    FOREIGN KEY (USER_ID) REFERENCES TB_USER(ID) ON DELETE CASCADE
);

CREATE INDEX idx_refresh_token_user_id
ON TB_REFRESH_TOKEN(USER_ID);

CREATE INDEX idx_refresh_token_expires_at
ON TB_REFRESH_TOKEN(EXPIRES_AT);

CREATE UNIQUE INDEX ux_refresh_token_user
ON TB_REFRESH_TOKEN(USER_ID)
WHERE REVOKED = FALSE;