CREATE TABLE TB_VIDEO_ANALYSIS (
    ID                BIGSERIAL       PRIMARY KEY,
    USER_ID           UUID            NOT NULL REFERENCES TB_USER(ID),
    EXERCISE_TYPE     VARCHAR(50)     NOT NULL,
    VIDEO_S3_KEY      TEXT            NOT NULL,
    STATUS            VARCHAR(20)     NOT NULL DEFAULT 'UPLOADED'
       CONSTRAINT CHK_VIDEO_ANALYSIS_STATUS
           CHECK (STATUS IN ('UPLOADED', 'PROCESSING', 'COMPLETED', 'FAILED')),
    CREATED_AT        TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    UPDATED_AT        TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

CREATE TABLE TB_ANALYSIS_RESULTS (
    ID                BIGSERIAL       PRIMARY KEY,
    ANALYSIS_ID       BIGINT          NOT NULL REFERENCES TB_VIDEO_ANALYSIS(ID) UNIQUE,
    MODEL_VERSION     VARCHAR(20)     NOT NULL,
    OVERALL_SCORE     NUMERIC(5,4)    NOT NULL
     CONSTRAINT CHK_ANALYSIS_RESULTS_SCORE
         CHECK (OVERALL_SCORE BETWEEN 0 AND 1),
    CLASSIFICATION    VARCHAR(20)     NOT NULL
     CONSTRAINT CHK_ANALYSIS_RESULTS_CLASSIFICATION
         CHECK (CLASSIFICATION IN ('GOOD', 'FAIR', 'POOR')),
    FEEDBACK          JSONB           NOT NULL,
    RAW_FEATURES      JSONB           NOT NULL,
    SCORED_AT         TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

CREATE TABLE TB_PIPELINE_ERRORS (
    ID                BIGSERIAL       PRIMARY KEY,
    ANALYSIS_ID       BIGINT          NOT NULL REFERENCES TB_VIDEO_ANALYSIS(ID),
    STAGE             VARCHAR(30)     NOT NULL
        CONSTRAINT CHK_PIPELINE_ERRORS_STAGE
            CHECK (STAGE IN ('EXTRACTION', 'SCORING')),
    ERROR_MESSAGE     TEXT,
    STACK_TRACE       TEXT,
    OCCURRED_AT       TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

CREATE INDEX IDX_VIDEO_ANALYSIS_USER       ON TB_VIDEO_ANALYSIS(USER_ID, CREATED_AT DESC);
CREATE INDEX IDX_VIDEO_ANALYSIS_STATUS     ON TB_VIDEO_ANALYSIS(STATUS);
CREATE INDEX IDX_ANALYSIS_RESULTS_ANALYSIS ON TB_ANALYSIS_RESULTS(ANALYSIS_ID);
CREATE INDEX IDX_PIPELINE_ERRORS_ANALYSIS  ON TB_PIPELINE_ERRORS(ANALYSIS_ID);