ALTER TABLE TB_VIDEO_ANALYSIS
DROP CONSTRAINT CHK_VIDEO_ANALYSIS_STATUS,
  ADD CONSTRAINT CHK_VIDEO_ANALYSIS_STATUS
    CHECK (STATUS IN ('CREATED', 'UPLOADED', 'PROCESSING', 'COMPLETED', 'FAILED', 'EXPIRED'));